spring:
  application:
    name: api-gateway-service
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 9191
  error:
    include-message: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
